USE aggregator;
CREATE TABLE IF NOT EXISTS roles
(
    id   BIGINT       NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);

INSERT IGNORE INTO roles (name)
VALUES ('ROLE_USER');
INSERT IGNORE INTO roles (name)
VALUES ('ROLE_ORGANIZER');
INSERT IGNORE INTO roles (name)
VALUES ('ROLE_ADMIN');
